version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/travel-conquest-be/
    overwrite: yes
    exclude:
      - scripts/**

permissions:
  - object: /home/ubuntu/travel-conquest-be/
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 60
      runas: ubuntu
