name: Run Test with Testcontainers

on:
  push:
    branches:
      - dev
      - issue#*
  pull_request:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create Docker Network
        run: docker network create dev_network

      - name: Pull Docker Images
        run: |
          docker pull redis:7.0
          docker pull mysql:8.0

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Make gradlew Executable
        run: chmod +x ./gradlew

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Run Unit Tests with Testcontainers
        run: |
          ./gradlew clean test