name: Run Test with Testcontainers

on:
  push:
    branches:
      - dev
      - issue#*
  pull_request:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    # Docker 서비스 활성화 (기본적으로 제공됨)
    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
      # 소스 코드 체크아웃
      - name: Checkout Code
        uses: actions/checkout@v4

      # Java 17 환경 설정
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      # Gradle 실행 권한 부여
      - name: Make gradlew Executable
        run: chmod +x ./gradlew

      # Docker Compose 설치 (Testcontainers 의존성을 해결하는 데 필요)
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # 유닛 테스트 실행 (Testcontainers 포함)
      - name: Run Unit Tests with Testcontainers
        run: |
          ./gradlew clean test
